import os
import logging
from typing import Optional, List, Dict, Any

from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import NoTranscriptFound, TranscriptsDisabled, VideoUnavailable, TooManyRequests, NoLanguageFound
import yt_dlp

from src.utils import TranscriptSegment

logger = logging.getLogger(__name__)

class VideoScraper:
    """
    A class to handle scraping operations for YouTube videos, including
    extracting video IDs, fetching transcripts, and downloading audio.
    """

    def __init__(self):
        """Initializes the VideoScraper."""
        pass # No specific initialization needed for now

    def get_video_id(self, url: str) -> Optional[str]:
        """
        Extracts the YouTube video ID from a given URL.

        Args:
            url: The full URL of the YouTube video.

        Returns:
            The video ID as a string, or None if the URL is invalid.
        """
        if "youtu.be" in url:
            video_id = url.split("/")[-1].split("?")[0]
        elif "v=" in url:
            video_id = url.split("v=")[1].split("&")[0]
        else:
            logger.error(f"Invalid YouTube URL format: {url}")
            return None
        logger.info(f"Extracted video ID: {video_id} from URL: {url}")
        return video_id

    def fetch_transcript(self, video_id: str) -> Optional[List[TranscriptSegment]]:
        """
        Fetches the transcript for a given YouTube video ID.

        Args:
            video_id: The ID of the YouTube video.

        Returns:
            A list of TranscriptSegment objects, or None if no transcript can be fetched.
        """
        logger.info(f"Attempting to fetch transcript for video ID: {video_id}")
        try:
            transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
            # Prioritize English, then any available transcript
            transcript_obj = None
            if 'en' in [t.language_code for t in transcript_list]:
                transcript_obj = transcript_list.find_transcript(['en'])
            else:
                # If no English transcript, try to get the first available one
                if transcript_list:
                    transcript_obj = transcript_list[0]
            
            if transcript_obj:
                transcript_data = transcript_obj.fetch()
                
                # Convert raw transcript data to list of TranscriptSegment objects
                formatted_transcript = [
                    TranscriptSegment(start=segment['start'], text=segment['text'])
                    for segment in transcript_data
                ]
                logger.info(f"Successfully fetched transcript for video ID: {video_id}")
                return formatted_transcript
            else:
                logger.warning(f"No suitable transcript found for video ID: {video_id}")
                return None

        except NoTranscriptFound:
            logger.warning(f"No transcript found for video ID: {video_id}. It might be autogenerated or unavailable.")
        except TranscriptsDisabled:
            logger.warning(f"Transcripts are disabled for video ID: {video_id}.")
        except VideoUnavailable:
            logger.error(f"Video with ID: {video_id} is unavailable.")
        except TooManyRequests:
            logger.error("Too many requests to YouTube Transcript API. Please try again later.")
        except NoLanguageFound:
            logger.warning(f"No language found for video ID: {video_id}.")
        except Exception as e:
            logger.error(f"An unexpected error occurred while fetching transcript for {video_id}: {e}", exc_info=True)
        return None

    def download_audio(self, url: str, output_path: str = "/tmp/audio.mp3") -> Optional[str]:
        """
        Downloads the audio of a YouTube video using yt-dlp.

        Args:
            url: The full URL of the YouTube video.
            output_path: The desired path and filename for the downloaded audio.

        Returns:
            The path to the downloaded audio file, or None if download fails.
        """
        logger.info(f"Attempting to download audio for {url} to {output_path}...")

        # Ensure the directory for output_path exists
        output_dir = os.path.dirname(output_path)
        if output_dir and not os.path.exists(output_dir):
            os.makedirs(output_dir, exist_ok=True)

        ydl_opts: Dict[str, Any] = {
            'format': 'bestaudio/best',
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '192',
            }],
            'outtmpl': output_path.replace('.mp3', ''), # yt-dlp automatically adds .mp3
            'quiet': True,
            'no_warnings': True,
        }

        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download([url])
            logger.info(f"Audio downloaded successfully to {output_path}.")
            return output_path
        except Exception as e:
            logger.error(f"Error downloading audio from {url}: {e}", exc_info=True)
            return None
